%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Administrator.PC-201708021221\Desktop\Assignment
%    3\Iris-data.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/09/25 20:19:22

%% Initialize variables.
filename = 'Iris-data.txt';
delimiter = ',';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
a = dataArray{:, 1};
b = dataArray{:, 2};
c = dataArray{:, 3};
d = dataArray{:, 4};
tempy = dataArray{:, 5};
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;